from fpdf import FPDF
from datetime import datetime, timezone
from typing import Dict, Any
from app.logs.logger import logger
from app.config.settings import settings

class ClinicalReportPDF(FPDF):
    def header(self):
        # Premium header style
        self.set_font('Arial', 'B', 16)
        self.set_text_color(40, 40, 40) # Dark gray
        self.cell(0, 10, 'OncoMouth AI - Clinical Report', 0, 1, 'L')
        self.set_draw_color(200, 200, 200)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by OncoMouth AI v{settings.metadata.version}', 0, 0, 'C')

def generate_pdf_report(prediction_data: Dict[str, Any]) -> bytes:
    """
    Generates a professional PDF report containing the prediction and metadata.
    """
    try:
        pdf = ClinicalReportPDF()
        pdf.add_page()
        
        # 1. Processing Metadata
        pdf.set_font("Arial", 'I', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, txt=f"Timestamp: {prediction_data.get('timestamp', datetime.now(timezone.utc).isoformat())}", ln=True)
        pdf.cell(0, 6, txt=f"Request ID: {prediction_data.get('request_id', 'N/A')}", ln=True)
        pdf.ln(5)
        
        # 2. AI Prediction Section
        pdf.set_font("Arial", 'B', 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, txt="AI Prediction Summary", ln=True)
        
        pdf.set_font("Arial", '', 12)
        pdf.cell(40, 8, txt="Prediction:", border=0)
        pdf.set_font("Arial", 'B', 12)
        
        # Color code prediction
        pred = prediction_data['prediction']
        if pred == 'Cancer':
            pdf.set_text_color(200, 50, 50)
        elif pred == 'PreCancer':
            pdf.set_text_color(200, 150, 50)
        else:
            pdf.set_text_color(50, 150, 50)
            
        pdf.cell(0, 8, txt=pred.upper(), ln=True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", '', 12)
        pdf.cell(40, 8, txt="Confidence:", border=0)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, txt=f"{prediction_data['confidence']:.1%}", ln=True)
        
        # 3. Probability Distribution
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 8, txt="Probability Distribution:", ln=True)
        pdf.set_font("Arial", '', 11)
        
        for k, v in prediction_data['probability_distribution'].items():
            pdf.cell(40, 6, txt=f"- {k}:", border=0)
            pdf.cell(0, 6, txt=f"{v:.1%}", ln=True)
            
        pdf.ln(2)
        pdf.cell(40, 6, txt="Calibration:", border=0)
        pdf.cell(0, 6, txt=f"{prediction_data['calibration_status']}", ln=True)
        
        # 4. Model Information
        pdf.ln(10)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, txt="Model Information:", ln=True)
        pdf.set_font("Arial", '', 10)
        pdf.cell(0, 6, txt=f"- Model Architecture: {settings.model_name}", ln=True)
        pdf.cell(0, 6, txt=f"- Version: {settings.metadata.version}", ln=True)
        pdf.cell(0, 6, txt=f"- ECE (Expected Calibration Error): {settings.metadata.ece}", ln=True)
        pdf.cell(0, 6, txt=f"- Inference Time: {prediction_data.get('inference_time_ms', 0)} ms", ln=True)
        
        # 5. Interpretation & Limitations
        pdf.ln(10)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, txt="AI Interpretation:", ln=True)
        pdf.set_font("Arial", '', 11)
        pdf.multi_cell(0, 6, txt=prediction_data['interpretation'])
        
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, txt="Limitations:", ln=True)
        pdf.set_font("Arial", '', 11)
        limitations = (
            "This model analyzes tissue morphology at the patch level using H&E staining. "
            "It does not account for patient demographic data, clinical history, or macroscopic "
            "lesion appearance. Ambiguous or borderline dysplastic cases may produce lower "
            "confidence scores and should be heavily scrutinized."
        )
        pdf.multi_cell(0, 6, txt=limitations)
        
        # 6. Clinical Disclaimer
        pdf.ln(15)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(0, 8, txt="DISCLAIMER:", ln=True, fill=True)
        pdf.set_font("Arial", '', 9)
        pdf.multi_cell(0, 5, txt=prediction_data.get('disclaimer', 'This AI prediction is intended to assist qualified healthcare professionals and is not a replacement for clinical judgment or formal histopathological diagnosis.'), fill=True)
        
        # 7. GradCAM Overlay Image
        if 'images' in prediction_data and 'gradcam' in prediction_data['images'] and prediction_data['images']['gradcam']:
            import base64
            import tempfile
            import os
            
            try:
                gradcam_b64 = prediction_data['images']['gradcam']
                img_data = base64.b64decode(gradcam_b64)
                
                # Write to a temporary file
                fd, temp_path = tempfile.mkstemp(suffix=".jpg")
                with os.fdopen(fd, 'wb') as f:
                    f.write(img_data)
                
                # Add image to PDF
                pdf.add_page()
                pdf.set_font("Arial", 'B', 12)
                pdf.cell(0, 8, txt="GradCAM++ Activation Map:", ln=True)
                pdf.ln(5)
                pdf.image(temp_path, x=10, w=100)
                
                # Clean up
                os.remove(temp_path)
            except Exception as img_e:
                logger.error(f"Failed to add GradCAM image to PDF: {img_e}")
        
        return bytes(pdf.output())
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise e
